spring.application.name=TP1

# Configuration serveur
server.port=8080

# Messages personnalisés
welcome.message=Bienvenue sur la gestion des personnes !
error.message=Le prénom et le nom de famille sont obligatoires.